openapi: 3.0.0
info:
  title: Admin Panel API
  version: 1.0.0
paths:
  /admin/users:
    get:
      summary: Get a list of users for the admin panel
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    email:
                      type: string
                    subscriptionPlan:
                      type: string
  /admin/payments:
    get:
      summary: Get a list of payments for the admin panel
      responses:
        '200':
          description: A list of payments
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    userId:
                      type: string
                    amount:
                      type: number
                    status:
                      type: string
