openapi: 3.0.3
info:
  title: Tarot Yorum API
  version: 0.1.0
paths:
  /api/daily:
    get:
      summary: Günlük tarot yorumu döndürür
      parameters:
        - in: query
          name: date
          required: false
          schema:
            type: string
            pattern: '^\\d{4}-\\d{2}-\\d{2}$'
          description: YYYY-MM-DD formatında tarih (boş ise bugün)
      responses:
        '200':
          description: Başarılı yanıt
          content:
            application/json:
              schema:
                type: object
                required: [date, cards, message]
                properties:
                  date:
                    type: string
                    example: '2025-09-11'
                  cards:
                    type: array
                    minItems: 3
                    maxItems: 3
                    items:
                      type: string
                  message:
                    type: string
        '422':
          description: Geçersiz tarih formatı
